'use client';

import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Lang = 'tr' | 'en';

const translations = {
  tr: {
    // Navbar
    home: 'Ana Sayfa',
    products: 'Ürünler',
    campaigns: 'Kampanyalar',
    bundles: 'Paketler',
    blog: 'Blog',
    calculator: 'Hesaplayıcı',
    contact: 'İletişim',
    login: 'Giriş Yap',
    register: 'Kayıt Ol',
    logout: 'Çıkış Yap',
    myAccount: 'Hesabım',
    cart: 'Sepet',
    search: 'Ürün ara...',
    notifications: 'Bildirimler',
    markAllRead: 'Tümünü okundu işaretle',
    noNotifications: 'Bildirim yok',
    // Hero
    heroBadge: "🌞 Türkiye'nin Güneş Enerji Mağazası",
    heroTitle1: 'Güneş Enerjisi ile',
    heroTitle2: 'Geleceği Aydınlat',
    heroSubtitle: 'En kaliteli güneş panelleri, bataryalar ve inverterler tek bir platformda. Uzman ekibimizle tasarruflu bir geleceğe adım at.',
    exploreProducts: 'Ürünleri Keşfet',
    freeConsultancy: 'Ücretsiz Danışmanlık',
    monthlySaving: 'Aylık Tasarruf',
    statInstallations: 'Kurulum',
    statBrands: 'Marka',
    statSatisfaction: 'Memnuniyet',
    statWarranty: 'Garanti',
    // Home sections
    categories: 'Kategoriler',
    allProducts: 'Tümü',
    featuredProducts: 'Öne Çıkan Ürünler',
    newArrivals: 'Yeni Gelenler',
    viewAll: 'Tümünü Gör',
    recentlyViewed: 'Son Baktıklarınız',
    whyUs: 'Neden Adalya Solar?',
    // Why us items
    whyWarrantyTitle: 'Orijinal Ürün Garantisi',
    whyWarrantyDesc: 'Tüm ürünlerimiz yetkili distribütörlerden temin edilmektedir.',
    whyDeliveryTitle: 'Hızlı ve Güvenli Teslimat',
    whyDeliveryDesc: '500₺ üzeri alışverişlerde ücretsiz kargo, sigortalı teslimat.',
    whySupportTitle: 'Uzman Teknik Destek',
    whySupportDesc: 'Satış öncesi ve sonrası uzman mühendis ekibimiz yanınızda.',
    whyPriceTitle: 'En İyi Fiyat Garantisi',
    whyPriceDesc: 'Aynı ürünü daha ucuza buldunuzsa fark iade ederiz.',
    // Calculator CTA
    freeCalcBadge: '⚡ Ücretsiz Hesaplama',
    freeCalcTitle: 'Size Kaç Panel Gerekiyor?',
    freeCalcSub: 'Elektrik faturanızı girin, sisteminizi anında hesaplayın.',
    calculate: 'Hesapla',
    // CTA Banner
    ctaTitle: 'Güneş Enerji Sisteminizi Tasarlayalım',
    ctaDesc: 'Uzman ekibimiz eviniz veya işyeriniz için en uygun güneş enerji sistemini ücretsiz hesaplar.',
    ctaBtn: 'Ücretsiz Enerji Analizi Al',
    // Product
    addToCart: 'Sepete Ekle',
    addedToCart: 'Sepete Eklendi!',
    addToFavorites: 'Favorilere Ekle',
    inFavorites: 'Favorilerde',
    share: 'Paylaş',
    inStock: 'Stokta var',
    outOfStock: 'Stok Tükendi',
    lastItems: 'Son adet!',
    notifyWhenAvailable: 'Stok geldiğinde haber ver',
    notifyMe: 'Haberdar Et',
    description: 'Ürün Açıklaması',
    specs: 'Teknik Özellikler',
    reviews: 'Değerlendirmeler',
    qa: 'Soru & Cevap',
    documents: 'Teknik Belgeler',
    relatedProducts: 'Benzer Ürünler',
    quickView: 'Hızlı Bakış',
    compare: 'Karşılaştır',
    removeFromCompare: 'Karşılaştırmadan Çıkar',
    compareMaxWarning: 'En fazla 3 ürün karşılaştırabilirsiniz.',
    // Cart
    myCart: 'Sepetim',
    emptyCart: 'Sepetiniz boş',
    emptyCartDesc: 'Henüz sepetinize ürün eklemediniz.',
    total: 'Toplam',
    subtotal: 'Ara Toplam',
    shipping: 'Kargo',
    freeShipping: 'Ücretsiz',
    checkout: 'Ödemeye Geç',
    couponCode: 'Kupon Kodu',
    apply: 'Uygula',
    remove: 'Kaldır',
    continueShopping: 'Alışverişe Devam Et',
    freeShippingOver: '500₺ ve üzeri ücretsiz kargo!',
    // Auth
    email: 'E-posta',
    password: 'Şifre',
    passwordConfirm: 'Şifre Tekrar',
    name: 'Ad Soyad',
    phone: 'Telefon Numarası',
    loginTitle: 'Tekrar Hoş Geldiniz!',
    loginSubtitle: 'Hesabınıza giriş yapın',
    registerTitle: 'Hesap Oluşturun',
    registerSubtitle: 'Ücretsiz kayıt olun, avantajlardan yararlanın',
    forgotPassword: 'Şifremi Unuttum',
    rememberMe: 'Beni hatırla',
    noAccount: 'Hesabınız yok mu?',
    haveAccount: 'Zaten hesabınız var mı?',
    orContinueWith: 'veya',
    signInWithGoogle: 'Google ile Giriş Yap',
    signUpWithGoogle: 'Google ile Kayıt Ol',
    agreeTerms: 'nı okudum ve kabul ediyorum.',
    termsLink: 'Kullanım Koşulları',
    privacyLink: 'Gizlilik Politikası',
    // Account
    myOrders: 'Siparişlerim',
    myFavorites: 'Favorilerim',
    myAddresses: 'Adreslerim',
    myProfile: 'Profil Bilgileri',
    // Footer
    footerDesc: "Güneş enerjisi çözümleri alanında Türkiye'nin önde gelen tedarikçisi. Kaliteli ürünler, uzman ekip, güvenilir hizmet.",
    footerCorporate: 'Kurumsal',
    footerAboutLink: 'Hakkımızda',
    footerFaq: 'SSS',
    footerCorporateLink: 'Kurumsal',
    footerProductCategories: 'Ürün Kategorileri',
    footerAllProducts: 'Tüm Ürünler →',
    footerContact: 'İletişim',
    footerWorkingHours: 'Çalışma Saatleri',
    footerWorkingHoursDetail: 'Pazartesi - Cumartesi: 09:00 - 18:00',
    footerNewsletter: 'Kampanyalardan Haberdar Ol',
    footerNewsletterDesc: 'Özel fırsatları kaçırma, e-postana gelsin',
    footerNewsletterPlaceholder: 'E-posta adresiniz',
    footerNewsletterBtn: 'Abone Ol',
    footerCopyright: '© 2026 Adalya Solar Enerji. Tüm hakları saklıdır.',
    footerPrivacy: 'Gizlilik Politikası',
    footerTerms: 'Kullanım Koşulları',
    footerReturn: 'İade Politikası',
    footerAbout: "Adalya Solar Enerji, güneş enerjisi sistemleri konusunda Türkiye'nin önde gelen e-ticaret platformudur.",
    allRights: 'Tüm hakları saklıdır.',
    // Common
    loading: 'Yükleniyor...',
    save: 'Kaydet',
    cancel: 'İptal',
    delete: 'Sil',
    edit: 'Düzenle',
    confirm: 'Onayla',
    close: 'Kapat',
    back: 'Geri',
    next: 'İleri',
    yes: 'Evet',
    no: 'Hayır',
    send: 'Gönder',
    sending: 'Gönderiliyor...',
    success: 'Başarılı',
    error: 'Hata',
    // Products page
    allCategories: 'Tüm Kategoriler',
    sortBy: 'Sırala',
    sortDefault: 'Varsayılan',
    sortPriceAsc: 'Fiyat: Düşükten Yükseğe',
    sortPriceDesc: 'Fiyat: Yüksekten Düşüğe',
    sortNewest: 'En Yeniler',
    sortRating: 'En Çok Değerlendirilen',
    noProducts: 'Ürün bulunamadı.',
    filters: 'Filtreler',
    priceRange: 'Fiyat Aralığı',
    brand: 'Marka',
    // Product detail
    writeReview: 'Değerlendirme Yaz',
    yourRating: 'Puanınız',
    reviewPlaceholder: 'Ürün hakkında düşüncelerinizi paylaşın...',
    submitReview: 'Değerlendirmeyi Gönder',
    submitting: 'Gönderiliyor...',
    loginToReview: 'Değerlendirme yapmak için giriş yapmanız gerekiyor.',
    noReviews: 'Henüz değerlendirme yok. İlk değerlendirmeyi sen yap!',
    helpful: 'Faydalı',
    sellerReply: 'Satıcı Yanıtı',
    askQuestion: 'Soru Sor',
    questionPlaceholder: 'Bu ürün hakkında merak ettiğinizi sorun...',
    sendQuestion: 'Soruyu Gönder',
    loginToAsk: 'Soru sormak için giriş yapmanız gerekiyor.',
    noQuestions: 'Henüz soru sorulmamış. İlk soruyu siz sorun!',
    notAnswered: 'Henüz yanıtlanmadı. En kısa sürede cevaplanacak.',
    addPhoto: 'Fotoğraf Ekle (maks. 5)',
    uploadingPhotos: 'Fotoğraflar yükleniyor...',
    downloadSpecs: 'Teknik Veri Sayfası İndir (PDF)',
    vatIncluded: 'KDV dahil fiyattır',
    bulkDiscount: 'Toplu Sipariş İndirimi',
    estimatedSavings: '⚡ Tahmini Tasarruf Hesabı',
    annualProduction: 'Yıllık üretim',
    annualSavings: 'Yıllık tasarruf',
    paybackPeriod: 'Kendini amorti süresi',
    years: 'yıl',
    notifyStock: 'Stok geldiğinde haber ver',
  },
  en: {
    // Navbar
    home: 'Home',
    products: 'Products',
    campaigns: 'Campaigns',
    bundles: 'Bundles',
    blog: 'Blog',
    calculator: 'Calculator',
    contact: 'Contact',
    login: 'Sign In',
    register: 'Sign Up',
    logout: 'Sign Out',
    myAccount: 'My Account',
    cart: 'Cart',
    search: 'Search products...',
    notifications: 'Notifications',
    markAllRead: 'Mark all as read',
    noNotifications: 'No notifications',
    // Hero
    heroBadge: "🌞 Turkey's Solar Energy Store",
    heroTitle1: 'Power Your Future',
    heroTitle2: 'with Solar Energy',
    heroSubtitle: 'The highest quality solar panels, batteries, and inverters on one platform. Take a step toward a sustainable future with our expert team.',
    exploreProducts: 'Explore Products',
    freeConsultancy: 'Free Consultation',
    monthlySaving: 'Monthly Savings',
    statInstallations: 'Installations',
    statBrands: 'Brands',
    statSatisfaction: 'Satisfaction',
    statWarranty: 'Warranty',
    // Home sections
    categories: 'Categories',
    allProducts: 'All',
    featuredProducts: 'Featured Products',
    newArrivals: 'New Arrivals',
    viewAll: 'View All',
    recentlyViewed: 'Recently Viewed',
    whyUs: 'Why Adalya Solar?',
    // Why us items
    whyWarrantyTitle: 'Original Product Warranty',
    whyWarrantyDesc: 'All our products are sourced from authorized distributors.',
    whyDeliveryTitle: 'Fast & Secure Delivery',
    whyDeliveryDesc: 'Free shipping on orders over ₺500, insured delivery.',
    whySupportTitle: 'Expert Technical Support',
    whySupportDesc: 'Our expert engineering team is with you before and after sale.',
    whyPriceTitle: 'Best Price Guarantee',
    whyPriceDesc: 'Found it cheaper elsewhere? We\'ll refund the difference.',
    // Calculator CTA
    freeCalcBadge: '⚡ Free Calculation',
    freeCalcTitle: 'How Many Panels Do You Need?',
    freeCalcSub: 'Enter your electricity bill and calculate your system instantly.',
    calculate: 'Calculate',
    // CTA Banner
    ctaTitle: 'Let Us Design Your Solar Energy System',
    ctaDesc: 'Our expert team will calculate the most suitable solar energy system for your home or business for free.',
    ctaBtn: 'Get Free Energy Analysis',
    // Product
    addToCart: 'Add to Cart',
    addedToCart: 'Added to Cart!',
    addToFavorites: 'Add to Favorites',
    inFavorites: 'In Favorites',
    share: 'Share',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    lastItems: 'items left!',
    notifyWhenAvailable: 'Notify me when available',
    notifyMe: 'Notify Me',
    description: 'Description',
    specs: 'Specifications',
    reviews: 'Reviews',
    qa: 'Q&A',
    documents: 'Documents',
    relatedProducts: 'Related Products',
    quickView: 'Quick View',
    compare: 'Compare',
    removeFromCompare: 'Remove from Compare',
    compareMaxWarning: 'You can compare up to 3 products.',
    // Cart
    myCart: 'My Cart',
    emptyCart: 'Your cart is empty',
    emptyCartDesc: 'You have not added any products to your cart yet.',
    total: 'Total',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    freeShipping: 'Free',
    checkout: 'Proceed to Checkout',
    couponCode: 'Coupon Code',
    apply: 'Apply',
    remove: 'Remove',
    continueShopping: 'Continue Shopping',
    freeShippingOver: 'Free shipping on orders over ₺500!',
    // Auth
    email: 'Email',
    password: 'Password',
    passwordConfirm: 'Confirm Password',
    name: 'Full Name',
    phone: 'Phone Number',
    loginTitle: 'Welcome Back!',
    loginSubtitle: 'Sign in to your account',
    registerTitle: 'Create an Account',
    registerSubtitle: 'Sign up for free and enjoy the benefits',
    forgotPassword: 'Forgot Password',
    rememberMe: 'Remember me',
    noAccount: 'Don\'t have an account?',
    haveAccount: 'Already have an account?',
    orContinueWith: 'or',
    signInWithGoogle: 'Sign in with Google',
    signUpWithGoogle: 'Sign up with Google',
    agreeTerms: 'I have read and agree to the',
    termsLink: 'Terms of Use',
    privacyLink: 'Privacy Policy',
    // Account
    myOrders: 'My Orders',
    myFavorites: 'My Favorites',
    myAddresses: 'My Addresses',
    myProfile: 'Profile Settings',
    // Footer
    footerDesc: "Turkey's leading supplier in solar energy solutions. Quality products, expert team, reliable service.",
    footerCorporate: 'Corporate',
    footerAboutLink: 'About Us',
    footerFaq: 'FAQ',
    footerCorporateLink: 'Corporate',
    footerProductCategories: 'Product Categories',
    footerAllProducts: 'All Products →',
    footerContact: 'Contact',
    footerWorkingHours: 'Working Hours',
    footerWorkingHoursDetail: 'Monday - Saturday: 09:00 - 18:00',
    footerNewsletter: 'Stay Updated on Campaigns',
    footerNewsletterDesc: 'Don\'t miss special offers, get them in your email',
    footerNewsletterPlaceholder: 'Your email address',
    footerNewsletterBtn: 'Subscribe',
    footerCopyright: '© 2026 Adalya Solar Energy. All rights reserved.',
    footerPrivacy: 'Privacy Policy',
    footerTerms: 'Terms of Use',
    footerReturn: 'Return Policy',
    footerAbout: 'Adalya Solar Energy is Turkey\'s leading e-commerce platform for solar energy systems.',
    allRights: 'All rights reserved.',
    // Common
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    confirm: 'Confirm',
    close: 'Close',
    back: 'Back',
    next: 'Next',
    yes: 'Yes',
    no: 'No',
    send: 'Send',
    sending: 'Sending...',
    success: 'Success',
    error: 'Error',
    // Products page
    allCategories: 'All Categories',
    sortBy: 'Sort By',
    sortDefault: 'Default',
    sortPriceAsc: 'Price: Low to High',
    sortPriceDesc: 'Price: High to Low',
    sortNewest: 'Newest',
    sortRating: 'Most Reviewed',
    noProducts: 'No products found.',
    filters: 'Filters',
    priceRange: 'Price Range',
    brand: 'Brand',
    // Product detail
    writeReview: 'Write a Review',
    yourRating: 'Your Rating',
    reviewPlaceholder: 'Share your thoughts about the product...',
    submitReview: 'Submit Review',
    submitting: 'Submitting...',
    loginToReview: 'You need to sign in to write a review.',
    noReviews: 'No reviews yet. Be the first to review!',
    helpful: 'Helpful',
    sellerReply: 'Seller Reply',
    askQuestion: 'Ask a Question',
    questionPlaceholder: 'Ask anything about this product...',
    sendQuestion: 'Send Question',
    loginToAsk: 'You need to sign in to ask a question.',
    noQuestions: 'No questions yet. Be the first to ask!',
    notAnswered: 'Not answered yet. Will be answered as soon as possible.',
    addPhoto: 'Add Photo (max. 5)',
    uploadingPhotos: 'Uploading photos...',
    downloadSpecs: 'Download Technical Data Sheet (PDF)',
    vatIncluded: 'VAT included',
    bulkDiscount: 'Bulk Order Discount',
    estimatedSavings: '⚡ Estimated Savings Calculator',
    annualProduction: 'Annual production',
    annualSavings: 'Annual savings',
    paybackPeriod: 'Payback period',
    years: 'years',
    notifyStock: 'Notify me when back in stock',
  },
} as const;

export type TranslationKey = keyof typeof translations.tr;

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: TranslationKey) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  lang: 'tr',
  setLang: () => {},
  t: (key) => key,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>('en');

  useEffect(() => {
    const saved = localStorage.getItem('lang') as Lang | null;
    if (saved === 'en' || saved === 'tr') setLangState(saved);
  }, []);

  const setLang = (l: Lang) => {
    setLangState(l);
    localStorage.setItem('lang', l);
    document.documentElement.lang = l;
  };

  const t = (key: TranslationKey): string => translations[lang][key] ?? translations.tr[key] ?? key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  return useContext(LanguageContext);
}
